// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: tnt_deploy_goods_info.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace TntDeploy
{

    [global::ProtoBuf.ProtoContract(Name = @"goods_info")]
    public partial class GoodsInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"goods_id", IsRequired = true)]
        public uint GoodsId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"name")]
        public byte[] Name
        {
            get { return __pbn__Name; }
            set { __pbn__Name = value; }
        }
        public bool ShouldSerializeName() => __pbn__Name != null;
        public void ResetName() => __pbn__Name = null;
        private byte[] __pbn__Name;

        [global::ProtoBuf.ProtoMember(3, Name = @"sex")]
        [global::System.ComponentModel.DefaultValue(0)]
        public uint Sex
        {
            get { return __pbn__Sex ?? 0; }
            set { __pbn__Sex = value; }
        }
        public bool ShouldSerializeSex() => __pbn__Sex != null;
        public void ResetSex() => __pbn__Sex = null;
        private uint? __pbn__Sex;

        [global::ProtoBuf.ProtoMember(4, Name = @"level_limit")]
        [global::System.ComponentModel.DefaultValue(0)]
        public uint LevelLimit
        {
            get { return __pbn__LevelLimit ?? 0; }
            set { __pbn__LevelLimit = value; }
        }
        public bool ShouldSerializeLevelLimit() => __pbn__LevelLimit != null;
        public void ResetLevelLimit() => __pbn__LevelLimit = null;
        private uint? __pbn__LevelLimit;

        [global::ProtoBuf.ProtoMember(5, Name = @"club_vip_level")]
        [global::System.ComponentModel.DefaultValue(0)]
        public int ClubVipLevel
        {
            get { return __pbn__ClubVipLevel ?? 0; }
            set { __pbn__ClubVipLevel = value; }
        }
        public bool ShouldSerializeClubVipLevel() => __pbn__ClubVipLevel != null;
        public void ResetClubVipLevel() => __pbn__ClubVipLevel = null;
        private int? __pbn__ClubVipLevel;

        [global::ProtoBuf.ProtoMember(6, Name = @"qb_2")]
        [global::System.ComponentModel.DefaultValue(0)]
        public int Qb2
        {
            get { return __pbn__Qb2 ?? 0; }
            set { __pbn__Qb2 = value; }
        }
        public bool ShouldSerializeQb2() => __pbn__Qb2 != null;
        public void ResetQb2() => __pbn__Qb2 = null;
        private int? __pbn__Qb2;

        [global::ProtoBuf.ProtoMember(7, Name = @"consume_type")]
        [global::System.ComponentModel.DefaultValue(0)]
        public uint ConsumeType
        {
            get { return __pbn__ConsumeType ?? 0; }
            set { __pbn__ConsumeType = value; }
        }
        public bool ShouldSerializeConsumeType() => __pbn__ConsumeType != null;
        public void ResetConsumeType() => __pbn__ConsumeType = null;
        private uint? __pbn__ConsumeType;

        [global::ProtoBuf.ProtoMember(8, Name = @"time_unit")]
        [global::System.ComponentModel.DefaultValue(0)]
        public uint TimeUnit
        {
            get { return __pbn__TimeUnit ?? 0; }
            set { __pbn__TimeUnit = value; }
        }
        public bool ShouldSerializeTimeUnit() => __pbn__TimeUnit != null;
        public void ResetTimeUnit() => __pbn__TimeUnit = null;
        private uint? __pbn__TimeUnit;

        [global::ProtoBuf.ProtoMember(9, Name = @"is_online")]
        [global::System.ComponentModel.DefaultValue(0)]
        public uint IsOnline
        {
            get { return __pbn__IsOnline ?? 0; }
            set { __pbn__IsOnline = value; }
        }
        public bool ShouldSerializeIsOnline() => __pbn__IsOnline != null;
        public void ResetIsOnline() => __pbn__IsOnline = null;
        private uint? __pbn__IsOnline;

        [global::ProtoBuf.ProtoMember(10, Name = @"can_buy")]
        [global::System.ComponentModel.DefaultValue(0)]
        public uint CanBuy
        {
            get { return __pbn__CanBuy ?? 0; }
            set { __pbn__CanBuy = value; }
        }
        public bool ShouldSerializeCanBuy() => __pbn__CanBuy != null;
        public void ResetCanBuy() => __pbn__CanBuy = null;
        private uint? __pbn__CanBuy;

        [global::ProtoBuf.ProtoMember(11, Name = @"can_recharge")]
        [global::System.ComponentModel.DefaultValue(0)]
        public uint CanRecharge
        {
            get { return __pbn__CanRecharge ?? 0; }
            set { __pbn__CanRecharge = value; }
        }
        public bool ShouldSerializeCanRecharge() => __pbn__CanRecharge != null;
        public void ResetCanRecharge() => __pbn__CanRecharge = null;
        private uint? __pbn__CanRecharge;

        [global::ProtoBuf.ProtoMember(12, Name = @"online_time")]
        public byte[] OnlineTime
        {
            get { return __pbn__OnlineTime; }
            set { __pbn__OnlineTime = value; }
        }
        public bool ShouldSerializeOnlineTime() => __pbn__OnlineTime != null;
        public void ResetOnlineTime() => __pbn__OnlineTime = null;
        private byte[] __pbn__OnlineTime;

        [global::ProtoBuf.ProtoMember(13, Name = @"offline_time")]
        public byte[] OfflineTime
        {
            get { return __pbn__OfflineTime; }
            set { __pbn__OfflineTime = value; }
        }
        public bool ShouldSerializeOfflineTime() => __pbn__OfflineTime != null;
        public void ResetOfflineTime() => __pbn__OfflineTime = null;
        private byte[] __pbn__OfflineTime;

        [global::ProtoBuf.ProtoMember(14, Name = @"privileged_plat_id_list")]
        public uint[] PrivilegedPlatIdLists { get; set; }

        [global::ProtoBuf.ProtoMember(15, Name = @"privileged_plat_is_online")]
        [global::System.ComponentModel.DefaultValue(0)]
        public uint PrivilegedPlatIsOnline
        {
            get { return __pbn__PrivilegedPlatIsOnline ?? 0; }
            set { __pbn__PrivilegedPlatIsOnline = value; }
        }
        public bool ShouldSerializePrivilegedPlatIsOnline() => __pbn__PrivilegedPlatIsOnline != null;
        public void ResetPrivilegedPlatIsOnline() => __pbn__PrivilegedPlatIsOnline = null;
        private uint? __pbn__PrivilegedPlatIsOnline;

        [global::ProtoBuf.ProtoMember(16, Name = @"privileged_plat_can_buy")]
        [global::System.ComponentModel.DefaultValue(0)]
        public uint PrivilegedPlatCanBuy
        {
            get { return __pbn__PrivilegedPlatCanBuy ?? 0; }
            set { __pbn__PrivilegedPlatCanBuy = value; }
        }
        public bool ShouldSerializePrivilegedPlatCanBuy() => __pbn__PrivilegedPlatCanBuy != null;
        public void ResetPrivilegedPlatCanBuy() => __pbn__PrivilegedPlatCanBuy = null;
        private uint? __pbn__PrivilegedPlatCanBuy;

        [global::ProtoBuf.ProtoMember(17, Name = @"privileged_plat_can_recharge")]
        [global::System.ComponentModel.DefaultValue(0)]
        public uint PrivilegedPlatCanRecharge
        {
            get { return __pbn__PrivilegedPlatCanRecharge ?? 0; }
            set { __pbn__PrivilegedPlatCanRecharge = value; }
        }
        public bool ShouldSerializePrivilegedPlatCanRecharge() => __pbn__PrivilegedPlatCanRecharge != null;
        public void ResetPrivilegedPlatCanRecharge() => __pbn__PrivilegedPlatCanRecharge = null;
        private uint? __pbn__PrivilegedPlatCanRecharge;

        [global::ProtoBuf.ProtoMember(18, Name = @"payment_terms")]
        [global::System.ComponentModel.DefaultValue(0)]
        public uint PaymentTerms
        {
            get { return __pbn__PaymentTerms ?? 0; }
            set { __pbn__PaymentTerms = value; }
        }
        public bool ShouldSerializePaymentTerms() => __pbn__PaymentTerms != null;
        public void ResetPaymentTerms() => __pbn__PaymentTerms = null;
        private uint? __pbn__PaymentTerms;

        [global::ProtoBuf.ProtoMember(19, Name = @"valid_time")]
        public byte[] ValidTime
        {
            get { return __pbn__ValidTime; }
            set { __pbn__ValidTime = value; }
        }
        public bool ShouldSerializeValidTime() => __pbn__ValidTime != null;
        public void ResetValidTime() => __pbn__ValidTime = null;
        private byte[] __pbn__ValidTime;

        [global::ProtoBuf.ProtoMember(20, Name = @"sort_priority")]
        [global::System.ComponentModel.DefaultValue(0)]
        public uint SortPriority
        {
            get { return __pbn__SortPriority ?? 0; }
            set { __pbn__SortPriority = value; }
        }
        public bool ShouldSerializeSortPriority() => __pbn__SortPriority != null;
        public void ResetSortPriority() => __pbn__SortPriority = null;
        private uint? __pbn__SortPriority;

        [global::ProtoBuf.ProtoMember(21, Name = @"suit_number")]
        [global::System.ComponentModel.DefaultValue(0)]
        public int SuitNumber
        {
            get { return __pbn__SuitNumber ?? 0; }
            set { __pbn__SuitNumber = value; }
        }
        public bool ShouldSerializeSuitNumber() => __pbn__SuitNumber != null;
        public void ResetSuitNumber() => __pbn__SuitNumber = null;
        private int? __pbn__SuitNumber;

        [global::ProtoBuf.ProtoMember(22, Name = @"bag_sort_priority")]
        [global::System.ComponentModel.DefaultValue(0)]
        public uint BagSortPriority
        {
            get { return __pbn__BagSortPriority ?? 0; }
            set { __pbn__BagSortPriority = value; }
        }
        public bool ShouldSerializeBagSortPriority() => __pbn__BagSortPriority != null;
        public void ResetBagSortPriority() => __pbn__BagSortPriority = null;
        private uint? __pbn__BagSortPriority;

        [global::ProtoBuf.ProtoMember(23, Name = @"status")]
        public byte[] Status
        {
            get { return __pbn__Status; }
            set { __pbn__Status = value; }
        }
        public bool ShouldSerializeStatus() => __pbn__Status != null;
        public void ResetStatus() => __pbn__Status = null;
        private byte[] __pbn__Status;

        [global::ProtoBuf.ProtoMember(24, Name = @"rank")]
        [global::System.ComponentModel.DefaultValue(0)]
        public uint Rank
        {
            get { return __pbn__Rank ?? 0; }
            set { __pbn__Rank = value; }
        }
        public bool ShouldSerializeRank() => __pbn__Rank != null;
        public void ResetRank() => __pbn__Rank = null;
        private uint? __pbn__Rank;

        [global::ProtoBuf.ProtoMember(25, Name = @"price_discount")]
        [global::System.ComponentModel.DefaultValue(0)]
        public uint PriceDiscount
        {
            get { return __pbn__PriceDiscount ?? 0; }
            set { __pbn__PriceDiscount = value; }
        }
        public bool ShouldSerializePriceDiscount() => __pbn__PriceDiscount != null;
        public void ResetPriceDiscount() => __pbn__PriceDiscount = null;
        private uint? __pbn__PriceDiscount;

        [global::ProtoBuf.ProtoMember(26, Name = @"vip_discount")]
        [global::System.ComponentModel.DefaultValue(0)]
        public uint VipDiscount
        {
            get { return __pbn__VipDiscount ?? 0; }
            set { __pbn__VipDiscount = value; }
        }
        public bool ShouldSerializeVipDiscount() => __pbn__VipDiscount != null;
        public void ResetVipDiscount() => __pbn__VipDiscount = null;
        private uint? __pbn__VipDiscount;

        [global::ProtoBuf.ProtoMember(27, Name = @"price_table")]
        public global::System.Collections.Generic.List<Price> PriceTables { get; } = new global::System.Collections.Generic.List<Price>();

        [global::ProtoBuf.ProtoMember(28, Name = @"goods_attr")]
        public global::System.Collections.Generic.List<GoodsAttr> GoodsAttrs { get; } = new global::System.Collections.Generic.List<GoodsAttr>();

        [global::ProtoBuf.ProtoMember(29, Name = @"description")]
        public byte[] Description
        {
            get { return __pbn__Description; }
            set { __pbn__Description = value; }
        }
        public bool ShouldSerializeDescription() => __pbn__Description != null;
        public void ResetDescription() => __pbn__Description = null;
        private byte[] __pbn__Description;

        [global::ProtoBuf.ProtoMember(30, Name = @"limit_id")]
        [global::System.ComponentModel.DefaultValue(0)]
        public uint LimitId
        {
            get { return __pbn__LimitId ?? 0; }
            set { __pbn__LimitId = value; }
        }
        public bool ShouldSerializeLimitId() => __pbn__LimitId != null;
        public void ResetLimitId() => __pbn__LimitId = null;
        private uint? __pbn__LimitId;

        [global::ProtoBuf.ProtoMember(31)]
        public byte[] subSystemId
        {
            get { return __pbn__subSystemId; }
            set { __pbn__subSystemId = value; }
        }
        public bool ShouldSerializesubSystemId() => __pbn__subSystemId != null;
        public void ResetsubSystemId() => __pbn__subSystemId = null;
        private byte[] __pbn__subSystemId;

        [global::ProtoBuf.ProtoContract()]
        public partial class Price : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"price_dq")]
            [global::System.ComponentModel.DefaultValue(0)]
            public uint PriceDq
            {
                get { return __pbn__PriceDq ?? 0; }
                set { __pbn__PriceDq = value; }
            }
            public bool ShouldSerializePriceDq() => __pbn__PriceDq != null;
            public void ResetPriceDq() => __pbn__PriceDq = null;
            private uint? __pbn__PriceDq;

            [global::ProtoBuf.ProtoMember(2, Name = @"price_gold")]
            [global::System.ComponentModel.DefaultValue(0)]
            public uint PriceGold
            {
                get { return __pbn__PriceGold ?? 0; }
                set { __pbn__PriceGold = value; }
            }
            public bool ShouldSerializePriceGold() => __pbn__PriceGold != null;
            public void ResetPriceGold() => __pbn__PriceGold = null;
            private uint? __pbn__PriceGold;

            [global::ProtoBuf.ProtoMember(3, Name = @"price_value")]
            [global::System.ComponentModel.DefaultValue(0)]
            public uint PriceValue
            {
                get { return __pbn__PriceValue ?? 0; }
                set { __pbn__PriceValue = value; }
            }
            public bool ShouldSerializePriceValue() => __pbn__PriceValue != null;
            public void ResetPriceValue() => __pbn__PriceValue = null;
            private uint? __pbn__PriceValue;

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class GoodsAttr : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"attr_type")]
            [global::System.ComponentModel.DefaultValue(0)]
            public uint AttrType
            {
                get { return __pbn__AttrType ?? 0; }
                set { __pbn__AttrType = value; }
            }
            public bool ShouldSerializeAttrType() => __pbn__AttrType != null;
            public void ResetAttrType() => __pbn__AttrType = null;
            private uint? __pbn__AttrType;

            [global::ProtoBuf.ProtoMember(2, Name = @"attr_value")]
            [global::System.ComponentModel.DefaultValue(0)]
            public uint AttrValue
            {
                get { return __pbn__AttrValue ?? 0; }
                set { __pbn__AttrValue = value; }
            }
            public bool ShouldSerializeAttrValue() => __pbn__AttrValue != null;
            public void ResetAttrValue() => __pbn__AttrValue = null;
            private uint? __pbn__AttrValue;

        }

    }

    [global::ProtoBuf.ProtoContract(Name = @"GOODS_INFO_ARRAY")]
    public partial class GoodsInfoArray : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"items")]
        public global::System.Collections.Generic.List<GoodsInfo> Items { get; } = new global::System.Collections.Generic.List<GoodsInfo>();

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
